credentials:
  usernames:
    web3owner:
      email: firepaladiner@gmail.com
      name: Dmitrii Kriukov
      password: $2b$12$GHUcLQ/BprmeiEZ03ab2NuvHJLBe0hJArLOP0Fi3WD4udpQ23q0JO #abc
      address: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8'
      private_key: '0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d'
    web3consumer:
      email: fire-paladin@mail.ru
      name: Thomas Aquinas
      password: $2b$12$isPBYeIVSQwUzcroH3jOt.gEJG2etLzbzAm6Ejm.kp4i7Y2lzDJSe #def
      address: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC'
      private_key: '0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a'
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
